# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FFBannerAutoScroll' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FFBannerAutoScroll
  
  pod 'SDWebImage'
  pod 'SDCycleScrollView'

  target 'FFBannerAutoScrollTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FFBannerAutoScrollUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
